### ISSUE TITLE
Headers() is not defined

### ISSUE THREAD

**Issue by JiantingFeng** [inkdropapp/inkdrop-live-export#2]
Hi, Takuya,

I tried to use this package, however, it seems don't compatible with Node v16 (as the Prerequisites in `README.md`),

When I try to use node 16: 
![SCR-20220921-svr](https://user-images.githubusercontent.com/36693163/192127341-50f9ca56-37dd-40b2-bdbb-720ef88a88b8.png)

It seems that `Headers()` is only supported by Node v18 and later, you can check the [Browser compability](https://developer.mozilla.org/en-US/docs/Web/API/Headers)

![image](https://user-images.githubusercontent.com/36693163/192127363-1aad2c20-ab8e-49ed-b884-ac9555984ba6.png)

After upgrading my node version, everything works. So I think maybe you should update the prerequisites, or use some third-party packages to manually import `Headers()` in order to make this plugin work with Node v16. :)

**Comment by craftzdog** [comment]
Oh thanks! I think it should update the prerequisites to Node >= 18.
