### ISSUE TITLE
Headers Constructor 

### ISSUE THREAD

**Issue by Ganesh156** [inkdropapp/inkdrop-live-export#3]
Headers Constructor is not called in index.ts file. 
It is giving me error.

**Comment by craftzdog** [comment]
I don't understand what you are talking about

**Comment by Ganesh156** [comment]
When I try to run live-export it shows an error as Headers is not defined.

I am using node version 18.9.0

**Comment by craftzdog** [comment]
`Headers` is supported from Node 18 as @JiantingFeng pointed out: https://github.com/inkdropapp/inkdrop-live-export/issues/2
So, I don't know why you get the error and I can't reproduce it.

**Comment by Ganesh156** [comment]
Ok, once I will check from my side.

**Comment by Ganesh156** [comment]
That error is solved now.
It was coming because my nvm has some issue.

**Comment by Ganesh156** [comment]
Now I am facing **fetch failed** can you please tell me what could be the reason?
I have set up the server config also in inkdrop config.cson file.
