### ISSUE TITLE
fetch is used but it is not called.

### ISSUE THREAD

**Issue by Ganesh156** [inkdropapp/inkdrop-live-export#4]
fetch function used but is is not called in the index.ts.

**Comment by JiantingFeng** [comment]
Hi, Ganesh, I saw your last issue. The `fetch` method is as `Headers()`, both of them are experimental features in node18, have you ever tried to update your node version? I'n using `v18.9.0` and it works well.

Maybe another possible solution is to manually install and import [`node-fetch`](https://github.com/node-fetch/node-fetch) package, which provides `Headers()` and `fetch` methods, however, you need to modify the `inkdrop-live-export` source code slightly.

**Comment by Ganesh156** [comment]
Hi, @JiantingFeng I installed the node-fetch package that the error is gone. Thank You.

Now I am facing the below-mentioned error, What could be the reason?

FetchError: request to http://127.0.0.1:19840/tags failed, reason: connect ECONNREFUSED 127.0.0.1:19840

**Comment by craftzdog** [comment]
You have to set up the local server https://docs.inkdrop.app/manual/accessing-the-local-database#accessing-via-http-advanced

**Comment by Ganesh156** [comment]
Hi, @craftzdog that also I did. Still, I am facing the issue.

**Comment by craftzdog** [comment]
I don't know what's wrong with what you reported.
`ECONNREFUSED` means the server is not reachable or not running.
You can check if the local server is running by adding `--enable-logging` option:

https://docs.inkdrop.app/manual/troubleshooting#enable-logging

**Comment by Ganesh156** [comment]
I fixed the issue thank you both of you. @craftzdog @JiantingFeng
