### ISSUE TITLE
404 for tags page

### ISSUE THREAD

**Issue by mhlozek** [inkdropapp/inkdrop-live-export#5]
Hi, thanks for wonderful app.

I have inkdrop blog up and running but still can not make tags work. 

I tried to add tag in Inkdrop app, then I stopped astro server and live-import task and run both tasks (server and live-import) again, but there are no tags exported.

Where could be the problem?

**Comment by craftzdog** [comment]
Check the following parts of the example:

https://github.com/craftzdog/craftzdog-uses/blob/main/tools/import.mjs#L24
https://github.com/craftzdog/craftzdog-uses/blob/main/src/pages/categories/%5Bid%5D.astro
